package lda;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

public class LDA_Classification extends javax.swing.JFrame {

    Object title[]={"R","G","B","D","Class"};

    DefaultTableModel tabelmodel=new DefaultTableModel(null,title);

    /** Creates new form LDA_Classification */
    public LDA_Classification() {
        initComponents();
        jTable1.setModel(tabelmodel);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LDA Classification");

        jLabel2.setText("Citra Training ");

        jButton1.setText("Training Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setText("Citra Testing");

        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton2.setText("Testing Data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel13.setText("Dataset Buah Jeruk");

        jLabel15.setText("Mean R");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel16.setText("Mean G");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel17.setText("Mean B");
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel18.setText("Diameter");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel19.setText("Kelas Jeruk");
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel20.setBorder(javax.swing.BorderFactory.createTitledBorder("Perhitungan Probabilitas Posterior"));

        jLabel21.setText("P (Kelas = Jeruk Lemon | X) =");

        jLabel22.setText("P (Kelas = Jeruk Manis | X) =");

        jLabel23.setText("P (Kelas = Jeruk Nipis | X) =");

        jLabel24.setText("Hasil Klasifikasi :");

        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "R", "G", "B", "D", "Class"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel2)
                        .addGap(385, 385, 385)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, 0, 0, Short.MAX_VALUE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 1707, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel21)
                                            .addGap(43, 43, 43)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextField7)
                                                .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                                .addComponent(jTextField8)
                                                .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel15)
                                                .addGap(43, 43, 43)
                                                .addComponent(jLabel16)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(jLabel17)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addComponent(jLabel19)))))
                                .addGap(1248, 1248, 1248))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)))
                        .addGap(8, 8, 8)))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(252, 252, 252))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public BufferedImage resize(BufferedImage img,int x,int y){

    BufferedImage dimg=new BufferedImage(x, y, BufferedImage.TYPE_INT_RGB);
    Graphics2D g=dimg.createGraphics();
    g.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
    g.drawImage(img, 0, 0,x,y,0,0,img.getWidth(),img.getHeight(),null);
    g.dispose();
    return dimg;
}

        extraksi_fitur ef=new extraksi_fitur();
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        final DefaultTableModel dataModel = (DefaultTableModel) jTable1.getModel();
        Thread a=new Thread(){
            public void run(){
                int count=0;
                int count2=0;
        final DefaultTableModel data= (DefaultTableModel) jTable1.getModel();
        for(int i=0;i<3;i++){
                    try {
                        ef.inputGambar("jerukLemon" + (i + 1) + ".jpg");
                        BufferedImage a=resize(ImageIO.read(new File("CitraJeruk/Data Training/jerukLemon" + (i + 1) + ".jpg")), jLabel1.getWidth(), jLabel1.getHeight());
                        ImageIO.write(a, "jpg", new File("ico"+count+".jpg"));
                        jLabel1.setIcon(new ImageIcon("ico"+count+++".jpg"));
                        a=resize(ImageIO.read(new File("abu2.jpg")), jLabel4.getWidth(), jLabel4.getHeight());
                        ImageIO.write(a, "jpg", new File("ico"+count+".jpg"));
                        jLabel4.setIcon(new ImageIcon("ico"+count+++".jpg"));
                        a=resize(ImageIO.read(new File("blackwhite.jpg")), jLabel14.getWidth(), jLabel14.getHeight());
                        ImageIO.write(a, "jpg", new File("ico"+count+".jpg"));
                        jLabel14.setIcon(new ImageIcon("ico"+count+++".jpg"));
                        
                        double rgb = extraksi_fitur.fiturlemon[i][0];
                        double rgb1 = extraksi_fitur.fiturlemon[i][1];
                        double rgb2 = extraksi_fitur.fiturlemon[i][2];
                        double diameter = extraksi_fitur.fiturlemon[i][3];
                        String nama = "jerukLemon";
                        data.addRow(new Object[]{rgb,rgb1,rgb2,diameter,nama});
                        sleep(1000);
                    } catch (IOException ex) {
                        Logger.getLogger(LDA_Classification.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(LDA_Classification.class.getName()).log(Level.SEVERE, null, ex);
                    }
    }
    for(int i=0;i<5;i++){
                    try {
                        ef.inputGambar("jerukManis" + (i + 1) + ".jpg");
                        BufferedImage a=resize(ImageIO.read(new File("CitraJeruk/Data Training/jerukManis" + (i + 1) + ".jpg")), jLabel1.getWidth(), jLabel1.getHeight());
                        ImageIO.write(a, "jpg", new File("ico"+count+".jpg"));
                        jLabel1.setIcon(new ImageIcon("ico"+count+++".jpg"));
                        a=resize(ImageIO.read(new File("abu2.jpg")), jLabel4.getWidth(), jLabel4.getHeight());
                        ImageIO.write(a, "jpg", new File("ico"+count+".jpg"));
                        jLabel4.setIcon(new ImageIcon("ico"+count+++".jpg"));
                        a=resize(ImageIO.read(new File("blackwhite.jpg")), jLabel14.getWidth(), jLabel14.getHeight());
                        ImageIO.write(a, "jpg", new File("ico"+count+".jpg"));
                        jLabel14.setIcon(new ImageIcon("ico"+count+++".jpg"));

                        double rgb = extraksi_fitur.fiturmanis[i][0];
                        double rgb1 = extraksi_fitur.fiturmanis[i][1];
                        double rgb2 = extraksi_fitur.fiturmanis[i][2];
                        double diameter = extraksi_fitur.fiturmanis[i][3];
                        String nama = "jerukManis";
                        data.addRow(new Object[]{rgb,rgb1,rgb2,diameter,nama});
                        sleep(1000);
                     } catch (IOException ex) {
                        Logger.getLogger(LDA_Classification.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(LDA_Classification.class.getName()).log(Level.SEVERE, null, ex);
                    }
    }
    for(int i=0;i<7;i++){
                    try {
                        ef.inputGambar("jerukNipis" + (i + 1) + ".jpg");
                        BufferedImage a=resize(ImageIO.read(new File("CitraJeruk/Data Training/JerukNipis" + (i + 1) + ".jpg")), jLabel1.getWidth(), jLabel1.getHeight());
                        ImageIO.write(a, "jpg", new File("ico"+count+".jpg"));
                        jLabel1.setIcon(new ImageIcon("ico"+count+++".jpg"));
                        a=resize(ImageIO.read(new File("abu2.jpg")), jLabel4.getWidth(), jLabel4.getHeight());
                        ImageIO.write(a, "jpg", new File("ico"+count+".jpg"));
                        jLabel4.setIcon(new ImageIcon("ico"+count+++".jpg"));
                        a=resize(ImageIO.read(new File("blackwhite.jpg")), jLabel14.getWidth(), jLabel14.getHeight());
                        ImageIO.write(a, "jpg", new File("ico"+count+".jpg"));
                        jLabel14.setIcon(new ImageIcon("ico"+count+++".jpg"));
                        double rgb = extraksi_fitur.fiturnipis[i][0];
                        double rgb1 = extraksi_fitur.fiturnipis[i][1];
                        double rgb2 = extraksi_fitur.fiturnipis[i][2];
                        double diameter = extraksi_fitur.fiturnipis[i][3];
                        String nama = "jerukNipis";
                        data.addRow(new Object[]{rgb,rgb1,rgb2,diameter,nama});
                        sleep(1000);
                     } catch (IOException ex) {
                        Logger.getLogger(LDA_Classification.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(LDA_Classification.class.getName()).log(Level.SEVERE, null, ex);
                    }
    }
            }
        };
        a.start();
    }//GEN-LAST:event_jButton1ActionPerformed
int u=0;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            
            JFileChooser jfc = new JFileChooser();
            jfc.setCurrentDirectory(new File("CitraJeruk/Data Testing"));
            jfc.showOpenDialog(null);
            File f = jfc.getSelectedFile();
            LDA l = new LDA();
            BufferedImage a=resize(ImageIO.read(f), jLabel8.getWidth(), jLabel8.getHeight());
                        ImageIO.write(a, "jpg", new File("icot"+u+".jpg"));
            jLabel8.setIcon(new ImageIcon("icot"+u+++".jpg"));
            double redf = 0;
            double greenf = 0;
            double bluef = 0;
            BufferedImage img = ImageIO.read(f);
            BufferedImage img2 = new BufferedImage(img.getWidth(), img.getHeight(), BufferedImage.TYPE_INT_RGB);
            BufferedImage img3 = new BufferedImage(img.getWidth(), img.getHeight(), BufferedImage.TYPE_INT_RGB);
            int[] coordinat1 = new int[img.getHeight()];
            int[] coordinat2 = new int[img.getHeight()];
            for (int i = 0; i < img.getHeight(); i++) {
                for (int j = 0; j < img.getWidth(); j++) {
                    Color c = new Color(img.getRGB(j, i), true);
                    int red = c.getRed();
                    int green = c.getGreen();
                    int blue = c.getBlue();
                    if (red != 255 && blue != 255 & green != 255) {
                        redf += red;
                        greenf += green;
                        bluef += blue;
                    }
                    int rata2 = Math.round((red + green + blue) / 3); //konversi citra menjadi grayscale
                    int black = 0;
                    if (rata2 > 230) { //thresholding
                        black = 0;
                    } else {
                        black = 255;
                    }
                    black = (black << 16) | (black << 8) | black;
                    img3.setRGB(j, i, black);
                    rata2 = (rata2 << 16) | (rata2 << 8) | rata2;
                    img2.setRGB(j, i, rata2);
                }
            }
            int change = 0;
            int count1 = 0;
            int count2 = 0;
            for (int i = 0; i < img.getHeight(); i++) {
                for (int j = 0; j < img.getWidth(); j++) {
                    Color c = new Color(img3.getRGB(j, i), true);
                    if (c.getRed() == 255 && change == 0) {
                        coordinat1[count1++] = j;
                        change = 1;
                    } else if (c.getRed() == 0 && change == 1) {
                        coordinat2[count2++] = j;
                        change = 0;
                    }
                }
            }
            int min = 99999;
            int max = 0;
            for (int i = 0; i < count1; i++) {
                if (min > coordinat1[i]) {
                    min = coordinat1[i];
                }
            }
            for (int i = 0; i < count2; i++) {
                if (max < coordinat2[i]) {
                    max = coordinat2[i];
                }
            }
            File abu2 = new File("abu2t.jpg");
            ImageIO.write(img2, "jpg", abu2);
            File blackwhite = new File("blackwhitet.jpg");
            ImageIO.write(img3, "jpg", blackwhite);
             BufferedImage b=resize(ImageIO.read(new File("abu2t.jpg")), jLabel10.getWidth(), jLabel10.getHeight());
                        ImageIO.write(b, "jpg", new File("icot1"+u+".jpg"));
             jLabel10.setIcon(new ImageIcon("icot1"+u+++".jpg"));
             BufferedImage c=resize(ImageIO.read(new File("blackwhitet.jpg")), jLabel9.getWidth(), jLabel9.getHeight());
                        ImageIO.write(c, "jpg", new File("icot2"+u+".jpg"));
             jLabel9.setIcon(new ImageIcon("icot2"+u+++".jpg"));
             jTextField1.setText(String.valueOf(redf/(img.getWidth()*img.getHeight())).substring(0,7));
             jTextField2.setText(String.valueOf(greenf/(img.getWidth()*img.getHeight())).substring(0,7));
             jTextField3.setText(String.valueOf(bluef/(img.getWidth()*img.getHeight())).substring(0,7));
             jTextField4.setText(String.valueOf(max-min));

            l.test(ef, redf/(img.getWidth()*img.getHeight()), greenf/(img.getWidth()*img.getHeight()), bluef/(img.getWidth()*img.getHeight()), max-min);
            if(l.hasil==1){
                jTextField5.setText("Lemon");
                jTextField9.setText("Jeruk Lemon");
            }
            else if(l.hasil == 2)
            {
                jTextField5.setText("Manis");
                jTextField9.setText("Jeruk Manis");
            }
            else if(l.hasil == 3)
            {
                jTextField5.setText("Nipis");
                jTextField9.setText("Jeruk Nipis");
            }
            jTextField6.setText(String.valueOf(l.f1).substring(0, 10));
            jTextField7.setText(String.valueOf(l.f2).substring(0, 10));
            jTextField8.setText(String.valueOf(l.f3).substring(0, 10));
        } catch (IOException ex) {
            Logger.getLogger(LDA_Classification.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LDA_Classification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

}
